#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_DIALOG1                             100
#define IDD_DIALOG2                             101
#define IDD_DIALOG3                             102
#define IDD_DIALOG4                             103
#define IDD_DIALOG5                             104
#define IDD_DIALOG6                             105
#define IDD_DIALOG7                             106
#define IDD_DIALOG8                             107
#define IDD_DIALOG9                             108
#define IDD_DIALOG10                            109
#define IDD_DIALOG11                            110
#define IDD_DIALOG12                            111
#define IDD_DIALOG13                            112
#define IDD_DIALOG14                            114
#define IDB_BITMAP2                             115
#define IDB_BITMAP3                             116
#define IDB_BITMAP1                             117
#define IDD_DIALOG15                            118
#define IDD_DIALOG16                            119
#define IDD_DIALOG17                            120
#define IDC_ADDRESS                             1000
#define IDC_BUTTON3                             1000
#define IDC_PIC                                 1000
#define IDC_RESULT3                             1000
#define IDC_CHECKBOX1                           1001
#define IDC_PIC2                                1001
#define IDC_BUTTON6                             1002
#define IDC_CHECKBOX4                           1002
#define IDC_EAX                                 1002
#define IDC_LIST1                               1003
#define IDC_EBX                                 1004
#define IDC_EDIT1                               1004
#define IDC_COMBO1                              1005
#define IDC_ECX                                 1005
#define IDC_RESULT2                             1005
#define IDC_COMBO2                              1006
#define IDC_EDX                                 1006
#define IDC_BUTTON1                             1007
#define IDC_ESI                                 1007
#define IDC_BUTTON2                             1008
#define IDC_CHECKBOX3                           1008
#define IDC_EDI                                 1008
#define IDC_BUTTON7                             1009
#define IDC_EBP                                 1009
#define IDC_BUTTON9                             1010
#define IDC_ESP                                 1010
#define IDC_EDIT2                               1011
#define IDC_EIP                                 1011
#define IDC_EDIT3                               1012
#define IDC_BUTTON5                             1013
#define IDC_CHECKBOX2                           1014
#define IDC_RESULT                              1014
#define IDC_EDIT4                               1015
#define IDC_LIST2                               1015
#define IDC_PROGRESS                            1016
#define IDC_BUTTON4                             1017
#define IDC_BUTTON8                             1018
#define IDC_PIC3                                1019
#define IDC_USERNAME                            1020
#define IDC_FILE                                1021
#define IDC_BUTTON12                            1022
#define IDC_BUTTON10                            1023
#define IDC_BUTTON11                            1024
#define IDC_PROGRESS1                           1025
#define IDC_VERSION                             1026
#define IDC_BUTTON13                            1027
#define IDC_BUTTON14                            1028
#define IDC_BUTTON15                            1029
#define IDC_BUTTON16                            1031
